export default allLocations = [
  {
    _id: 1,
    title: 'Madhav Techno Labs',
    city: 'Rajkot',
    state: 'Gujarat',
    country: 'india',
  },
  {
    _id: 2,
    title: 'Rajkot',
    city: 'Rajkot',
    state: 'Gujarat',
    country: 'india',
  },
  {
    _id: 3,
    title: 'Rajkot Airport',
    city: 'Rajkot',
    state: 'Gujarat',
    country: 'india',
  },
  {
    _id: 4,
    title: 'Rajkot Bus Port',
    city: 'Rajkot',
    state: 'Gujarat',
    country: 'india',
  },
  {
    _id: 5,
    title: 'Jamnagar',
    city: 'Jamnagar',
    state: 'Gujarat',
    country: 'india',
  },
  {
    _id: 6,
    title: 'Jamnagar Bus Port',
    city: 'Jamnagar',
    state: 'Gujarat',
    country: 'india',
  },
  {
    _id: 7,
    title: 'Jamnagar Bus Port',
    city: 'Jamnagar',
    state: 'Gujarat',
    country: 'india',
  },
  {
    _id: 8,
    title: 'Ahmedabad',
    city: 'Ahmedabad',
    state: 'Gujarat',
    country: 'india',
  },
  {
    _id: 9,
    title: 'Ahmedabad Bus Port',
    city: 'Ahmedabad',
    state: 'Gujarat',
    country: 'india',
  },
  {
    _id: 10,
    title: 'Ahmedabad Bus Port',
    city: 'Ahmedabad',
    state: 'Gujarat',
    country: 'india',
  },
]
